Data:
  database : /scratch/c.sistc3/AMI-diarization-setup/pyannote/database.yml

Training:
  duration : 5
  max_num_speakers : 4
  batch_size : 32
  epochs : 1
  learning_rate : 0.0001
  sampling_rate : 16000
  device : cpu
  experiment_name : Speaker-Segmentation
  run_name : Baseline
  
